package lean.util.MessageFactory;

public enum Message {
    LOGIN_FAILED,
    LOGIN_SUCCESS,
    ACCOUNT_CREATED,
    REGISTER_FAILED,
    INVALID_PASSWORD,
    USER_FROM_ID_RETRIEVED,
    USER_PRIVILEGE_CHANGED,
    USER_NOT_PRIVILEGED,
    USER_LANGUAGE_CHANGED,
    USER_PASSWORD_CHANGED,
    PASSWORD_NOT_NEW
}
